name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"


    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          pip install pipenv
          pip install build
          pipenv install --dev
      - name: Test
        run: |
          pipenv run pytest
      - name: Build
        run: |
          python -m build
